### ISSUE TITLE
Unity 2017.1 transparent objects

### ISSUE THREAD

**Issue by jazznazz** [cCharkes/StochasticScreenSpaceReflection#1]
These reflections look SO much better than the Unity standard! Thank you for the hard work ! 
There's an issue with transparent Standard shader objects though - Unity 2017.1: 
![image](https://user-images.githubusercontent.com/2911330/29498039-d6d50a6a-85fc-11e7-9c22-9755cac64846.png)

**Comment by volfin** [comment]
I see this as well. It seems to be caused by combining SSSR with Unity's Post-Processing Stack. Removing the Post-Processing stack fixes the issue.

**Comment by volfin** [comment]
After some experimentation, I found that commenting out line 404 in StochasticSSR allows it to work with the post processing stack. 

Of course removing the [ImageEffectOpaque] attribute seems counterintuitive, but perhaps a clue to a solution. Maybe the Post-Processing stack already applies this setting.  

I notice now tables have turned, transparency shows through only when Post-Processing is *not* present. So odd.

**Comment by Xerxes1138** [comment]
Hi,

I'm aware of this issue and looking for a solution.

As a temporary solution I've tested with this version https://github.com/Unity-Technologies/PostProcessing/tree/v2 of the Post-Processing stack and it looks like it is working in my projects.

About [ImageEffectOpaque], from my observation, removing it confuse the Post-Processing stack and force SSSR to render in LDR instead of HDR.

Thank you for reporting this guys, I'll keep you informed.

**Comment by jazznazz** [comment]
Thanks for the quick reply ! 
I just tested with PostProcessing-2 stack, and this is the result: 
![image](https://user-images.githubusercontent.com/2911330/29871716-8344eb54-8d95-11e7-87ab-d0a250c09375.png)

**Comment by volfin** [comment]
I tried it with the Postprocessing stack V2, and it seems fine. but I only put Antialiasing (FXAA) and color grading, like the original scene. Perhaps it's one particular effect it's conflicting with?

**Comment by jazznazz** [comment]
You're right ! I just tested, it's caused by Unity's TAA , the problem went away on  Post-Processing Stack V1 and V2 also(When not using TAA).

**Comment by simeonradivoev** [comment]
I has to do with the camera's non Jittered Projection Matrix. The it should not be set with a projection matrix derived from `GL.GetGPUProjectionMatrix` like [here](https://github.com/cCharkes/StochasticScreenSpaceReflection/blob/ff2bf2416927b14262a2016fa93d13dbe3ece400/Assets/Extensions/StochasticSSR/Scripts/StochasticSSR.cs#L333). It messes up transparent objects.

**Comment by volfin** [comment]
So how would you go about fixing that? Where else would you get a projection matrix? It seems it's even worse now with the latest release.

**Comment by simeonradivoev** [comment]
remove the line [here](https://github.com/cCharkes/StochasticScreenSpaceReflection/blob/ff2bf2416927b14262a2016fa93d13dbe3ece400/Assets/Extensions/StochasticSSR/Scripts/StochasticSSR.cs#L333).

**Comment by volfin** [comment]
Thanks, that did fix the issue.

**Comment by Xerxes1138** [comment]
I've removed the line in the main branch.
